### ISSUE TITLE
Sections and subsections w/o numbering

### ISSUE THREAD

**Issue by filippobistaffa** [sean-chester/H2020-MSCA-IF-2016#1]
With this template sections and subsections (e.g., Excellence, Impact, Implementation) appear without numbers, but according to [this template](http://ec.europa.eu/research/participants/data/ref/h2020/call_ptef/pt/h2020-call-pt-msca-if_en.pdf) I guess section and subsection numbers should be there.

**Comment by sean-chester** [comment]
@filippobistaffa Thanks for raising this issue. The section and subsection numbers ought to appear when using this template. Can you perhaps give a minimum working example that I can use to replicate the problem?

**Comment by filippobistaffa** [comment]
I suspect this issue depends on the texlive version. In fact, with the most recent version on Ubuntu 16.04 (2015.20160320) numbers do not appear. This can be reproduced by just cloning the repository and running build.sh ([result PDF](https://github.com/sean-chester/H2020-MSCA-IF-2016/files/393391/IF-2016-Part_B.pdf)). With version 2013.20140215 (most recent version on Ubuntu 14.04) numbers appear just fine.

**Comment by sean-chester** [comment]
Can you check whether [this StackOverflow solution](http://tex.stackexchange.com/a/300259/84485) solves this problem? (I'm running in a different environment, so I can't check right away.)

**Comment by sean-chester** [comment]
Please try the update on the issue1 branch where I have incorporated the aforementioned StackOverflow solution and let me know if you get the section numbers back.

**Comment by filippobistaffa** [comment]
Yes, the update seems to fix the problem, as you can see [here](https://github.com/sean-chester/H2020-MSCA-IF-2016/files/393618/IF-2016-Part_B.pdf).
Thanks.

**Comment by sean-chester** [comment]
Great! Thanks for bringing this up! I'll close the issue now and merge the changes onto the _master_ branch.
